sudo: required
dist: trusty
language: bash
matrix:
  include:
  - os: linux
  - os: osx
before_install:
  - curl -L https://github.com/holgern/travis-texlive/releases/download/2017-07-05_09/texlive.tar.xz | tar -JxC ~
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];  then PATH=$HOME/texlive/bin/x86_64-darwin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];  then PATH=$HOME/texlive/bin/x86_64-linux:$PATH; fi
script:
   - make clean
   - make BUILD_STRATEGY=pdflatex
   - make clean
   - make