# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# https://ci.appveyor.com/project/holgern/pyedflib

# This file is built on the template here:
# http://python-packaging-user-guide.readthedocs.org/en/latest/appveyor/

cache:
  - c:\miktex -> appveyor.yml

install:
  # Install miktex to get pdflatex, if we don't get it from the cache
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe appveyor DownloadFile http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable.exe
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe 7z x miktex-portable.exe -oC:\miktex >NUL
  - set "PATH=%PATH%;c:\miktex\texmfs\install\miktex\bin"
  # autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
  # this adds this to the registry!
  - initexmf --set-config-value "[MPM]AutoInstall=1"
 
# to run your custom scripts instead of automatic MSBuild
build_script:
  - compile-thesis-windows.bat thesis

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: '*.pdf'
